volumes:
  tracking_logs:
    driver: local
    driver_opts:
        type: ext4
        device: "/var/log/logs_for_xapi_docker"
        o: bind
  old_logs:
    driver: local
    driver_opts:
        type: ext4
        device: "/mnt/old_logs"
        o: bind

services:
  xapi_bridge:
    build: .
    ports:
      - "9091:9090"
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - log_dir=${LOG_DIR}
      - log_dates=${LOG_DATES}
      - TZ=Europe/Moscow
    volumes:
      - tracking_logs:/var/log
      - old_logs:/var/old_logs
    develop:
      watch:
        - action: sync+restart
          path: ./xapi_bridge
          target: /app/xapi_bridge
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: build.sh          
